# Hafif bir Nginx base image kullanın
FROM nginx:alpine

# Nginx'in HTML dosyalarını sakladığı klasöre kopyalayın
COPY . /usr/share/nginx/html

# Nginx'i başlatın (Nginx default olarak başlar, bu yüzden CMD gerekli değil)
EXPOSE 80

