version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres1
      POSTGRES_PASSWORD: 65263
      POSTGRES_DB: ToDoApp
    ports:
      - "5432:5432"
    networks:
      - app-network

  backend:
    build: ./app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ToDoApp
      SPRING_DATASOURCE_USERNAME: postgres1
      SPRING_DATASOURCE_PASSWORD: 65263
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build: ./todoApp Frontend
    ports:
      - "5500:80"
    depends_on:
      - backend
    networks:
      - app-network
      networks:
app-network:
  driver: bridge
